[package]
name = "topset"
version = "0.4.0"
authors = ["Xophe <christophe.dousson@orange.com>"]
edition = "2021"
license = "MIT"
description = "Top N selector"
repository = "https://github.com/XopheD/topset"
documentation = "https://docs.rs/topset"
